#!/bin/zsh

# completion
autoload -U compinit
compinit

# correction
setopt correctall

# prompt
autoload -U promptinit
promptinit
prompt adam2

# Enable aliases
. ~/.zsh/.aliases

# Enable vim commands in zsh.
bindkey -v
export KEYTIMEOUT=1

# fix colors
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# Set path
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/opt:$PATH
export PATH=/opt/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/local/opt/qt5/bin:$PATH
export PATH=/usr/local/spark-2.1.0-bin-hadoop2.7/bin:$PATH
export PATH=~/Library/Python/2.7/bin:$PATH
# Add laravel executable to path
export PATH=$HOME/.composer/vendor/bin:$PATH

# Set php to use homebrew's php71
export PATH="$(brew --prefix homebrew/php/php71)/bin:$PATH"
